spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.125.250.212:3360/SEA?verifyServerCertificate=false&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: BugKillers
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    #    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true
    database: mysql
